version: "3"

services:
  golang:
    build: .
    user: root
    working_dir: /app
    volumes:
      - ./:/app
    container_name: nikiti_books_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      HOSTNAME: db
  db:
    container_name: nikiti_books_db
    image: postgres
    platform: linux/x86_64
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
