version: "3"

services:
  golang:
    build: .
    user: root
    working_dir: /app
    volumes:
      - ./:/app
    container_name: nikiti_books_api_test
    tty: true
    stdin_open: true
    command: bash
    restart: always
    depends_on:
      - db_test
    ports:
      - "7080:7080"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      HOSTNAME: db
  db_test:
    container_name: nikiti_books_db_test
    image: mongo
    platform: linux/x86_64
    restart: always
    ports:
      - "37017:37017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
