// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	customerror "github.com/beto-ouverney/nikiti-books/customerror"
	entity "github.com/beto-ouverney/nikiti-books/entity"

	mock "github.com/stretchr/testify/mock"
)

// IBookModel is an autogenerated mock type for the IBookModel type
type IBookModel struct {
	mock.Mock
}

// Add provides a mock function with given fields: book
func (_m *IBookModel) Add(book *entity.Book) *customerror.CustomError {
	ret := _m.Called(book)

	var r0 *customerror.CustomError
	if rf, ok := ret.Get(0).(func(*entity.Book) *customerror.CustomError); ok {
		r0 = rf(book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerror.CustomError)
		}
	}

	return r0
}

// FindAll provides a mock function with given fields:
func (_m *IBookModel) FindAll() (*[]entity.Book, *customerror.CustomError) {
	ret := _m.Called()

	var r0 *[]entity.Book
	if rf, ok := ret.Get(0).(func() *[]entity.Book); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.Book)
		}
	}

	var r1 *customerror.CustomError
	if rf, ok := ret.Get(1).(func() *customerror.CustomError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*customerror.CustomError)
		}
	}

	return r0, r1
}

// FindBook provides a mock function with given fields: param
func (_m *IBookModel) FindBook(param string) (*entity.Book, *customerror.CustomError) {
	ret := _m.Called(param)

	var r0 *entity.Book
	if rf, ok := ret.Get(0).(func(string) *entity.Book); ok {
		r0 = rf(param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Book)
		}
	}

	var r1 *customerror.CustomError
	if rf, ok := ret.Get(1).(func(string) *customerror.CustomError); ok {
		r1 = rf(param)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*customerror.CustomError)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewIBookModel interface {
	mock.TestingT
	Cleanup(func())
}

// NewIBookModel creates a new instance of IBookModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIBookModel(t mockConstructorTestingTNewIBookModel) *IBookModel {
	mock := &IBookModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
